export const APPLICATION_STATUS = {
  IN_PROGRESS: "IN_PROGRESS",
  REJECTED: "REJECTED",
  APPROVED: "APPROVED",
};

export const APPLICATION_STAGE = {
  APPLICATION_FORM: "APPLICATION_FORM",
  INTERVIEW: "INTERVIEW",
  COMPLIANCE: "COMPLIANCE",
};
